### ISSUE TITLE
there is no fzf binaries for ppc64le architecture

### ISSUE THREAD

**Issue by leitao** [junegunn/fzf-bin#2]
This is what happens when I try to reverse search in fish:

> ➜  ~ fzf not yet installed. Installing now, please wait...No matches for wildcard “Linux\ i*86”.
> ~/.config/fish/functions/__fzf_install.fish (line 10):       case Linux\ i*86
>                                                                   ^
> in function “__fzf_install”
> 	called on line 4 of file ~/.config/fish/functions/__fzf_ctrl_r.fish
> 
> in function “__fzf_ctrl_r”
> 	called on standard input
> 
> No matches for wildcard “i*86”.
> ~/.config/fish/functions/__fzf_install.fish (line 12):       case Darwin\  i*86
>                                                                            ^
> in function “__fzf_install”
> 	called on line 4 of file ~/.config/fish/functions/__fzf_ctrl_r.fish
> 
> in function “__fzf_ctrl_r”
> 	called on standard input
> 
> fatal: destination path '/home/ubuntu/.fzf' already exists and is not an empty directory.

I have access to ppc64le machine and I can compile fzf for it. how can I help here?

**Comment by junegunn** [comment]
I'll be the one keep releasing the official binaries so I should be able to cross-compile them on my machine and it looks like it's not trivial to build ppc binaries on my environment. If you can extend the [Makefile](https://github.com/junegunn/fzf/blob/master/src/Makefile) to build ppc binaries as well on my machine (OS X), I'll include them in the release process. (`make release linux android` is the command I use to build OS X, Linux, and Android binaries.)

And it looks like you're using some kind of package manager that I have no control over. I think you should contact the maintainer of it, and suggest that it should build the binary from the source if there's no prebuilt binary for the platform.
